apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: id4l8e8yi-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:45d51b46f9d11277893a0f163768cf2b7cd584b5@sha256:724f2930ef25b085a39bd28c487d42716ad58e699db6aea2726a664be0e1250e
          name: container-image
